# Generated by Django 2.1.4 on 2018-12-17 18:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('snippet', models.TextField(null=True)),
                ('source', models.CharField(max_length=1024)),
                ('published_at', models.DateTimeField()),
                ('uid', models.CharField(db_index=True, max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('refresh_frequency', models.IntegerField(default=2, help_text='minimum number of hours between refreshes')),
                ('expired_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.Target')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usertarget',
            unique_together={('user', 'target_keyword')},
        ),
    ]
